### ISSUE TITLE
Bug adding new feedback

### ISSUE THREAD

**Issue by diptim01** [diptim01/feedback-review-app#10]
When I edit a feedback, and later intend to add a new one, it replaces the edited one. Fancy bug

**Comment by ghost** [comment]
## Hi master diptim
### Can I take this issue ?

**Comment by ghost** [comment]
## by the way if you want I can make restful api

**Comment by diptim01** [comment]
oh awesome. I had fixed the issue. Currently building on pipeline

However, I have pending projects we can work on. I will add and tag when I start shortly

**Comment by diptim01** [comment]
1. solved

**Comment by ghost** [comment]
## That's great I'll be waiting 👍
